FROM python:3.12

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia todos los archivos del proyecto
COPY . .

# Instala las dependencias necesarias
RUN pip install -r requirements.txt

# Comando para ejecutar el cliente
CMD ["python", "-u", "src/client.py"]